id = "freezed-snippets"
name = "Freezed Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Steeven Lopez <stee-ven_94@outlook.com>"]
description = "Collection of Freezed snippets for Flutter/Dart development on the Zed editor."
repository = "https://github.com/OppositeDragon/freezed-snippets"
snippets = "./snippets/dart.json"
